"""add composite index on ticker and timestamp

Revision ID: 17c842b6e158
Revises: ca0e62fcb927
Create Date: 2026-05-22 18:23:58.888926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c842b6e158'
down_revision: Union[str, None] = 'ca0e62fcb927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_analysis_ticker_ts', 'analysis_results', ['ticker', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_ticker_ts', table_name='analysis_results')
    # ### end Alembic commands ###
