"""add risk_free_rate column

Revision ID: f66078771d75
Revises: 17c842b6e158
Create Date: 2026-05-22 18:40:52.480403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66078771d75'
down_revision: Union[str, None] = '17c842b6e158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('risk_free_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'risk_free_rate')
    # ### end Alembic commands ###
